### ISSUE TITLE
Pasting GPS in Alliance Chat Crashes Client

### ISSUE THREAD

**Issue by subbob** [DraconisCluster/DX-Issues#10]
** tl; dr **
Pasting GPS point into Alliance chat immediate disconnects client

** Full info **
Screenshot and Video Clip below.

**Screenshots**
--If applicable, add screenshots to help explain your problem.--
![image](https://github.com/DraconisCluster/DX-Issues/assets/5113030/ab1903d6-3840-4e9c-b1ba-3c9649532ed3)

https://github.com/DraconisCluster/DX-Issues/assets/5113030/6baddabc-e510-4c27-b5c3-5194be27299d

**Comment by subbob** [comment]
I first pasted it into Faction chat to show that it works there.

**Comment by Terif1** [comment]
This will be fixed when we next push nations

**Comment by subbob** [comment]
Could be coincidental, but I mentioned GPS in alliance chat "I will send you GPS via DM" and my client immediately unloaded.  (Lesson learned, I will NOT  use that acronym in alliance chat for now) lol

**Comment by Terif1** [comment]
yeah, sounds about right

**Comment by Terif1** [comment]
The parser basically looks for "GPS" in severe chat message and if it finds it, it tries to extract a gps from it

**Comment by Terif1** [comment]
Even as simple as "Gps" would be safe

**Comment by subbob** [comment]
Yea, immediately after posting this I wrote in game alliance chat. 
_Do not use G P S (without spaces) in chat_. 
'cause I did not want to assume it was case sensitive, figured it was, but not willing another D/C to test it

**Comment by subbob** [comment]
![image](https://github.com/DraconisCluster/DX-Issues/assets/5113030/fb0778ff-31a1-4b1a-8341-0cf537e9f25b)
At this point could we just **REMOVE** the parser from Alliance chat?

Not just for me, but for the untold number of players that may be getting force unloaded and don't know why.
https://discord.com/channels/516135382191177728/917984542432833566/1198342488109359114

**Comment by Terif1** [comment]
Did I not push the fix to it?

**Comment by Terif1** [comment]
Crap I didnt

**Comment by Terif1** [comment]
It's fixed on git just needs someone to push it

**Comment by subbob** [comment]
Thanks.

**Comment by Synirrr** [comment]
Have we pushed this fix? If so we should close this

**Comment by Terif1** [comment]
I think so

**Comment by Terif1** [comment]
closing as fixed
