### ISSUE TITLE
Unable to hangar around CIVL faction

### ISSUE THREAD

**Issue by draconb** [DraconisCluster/DX-Issues#12]
CIVL, even neutral, is preventing hangaring

Prevents hangaring near nation HQ and also ice haulers are spawning on people and prevent hangaring their base since they never leave.

**Comment by Terif1** [comment]
That's...physically not how that works

**Comment by Terif1** [comment]
As long as people are actually neutral to civl it shouldn't matter

**Comment by draconb** [comment]
I thought the same, but it is

**Comment by Terif1** [comment]
Hmm

**Comment by Terif1** [comment]
Only thing I could think is the faction is neutral but the player isn't, but that'd have a whole other can of worms

**Comment by Terif1** [comment]
Like everything else like docking to civl would be broken

**Comment by draconb** [comment]
Nope, what connected and used store at nation hq. Left and went to hangar, couldn't within 25km of it

**Comment by Terif1** [comment]
We will (I guess) need someone to go in and figure out why for this, cause there is no reason for it

**Comment by Synirrr** [comment]
@Terif1 Will this be fixed with the fork you created of the Quantum Hangar?

**Comment by Terif1** [comment]
I mean if there was anything to fix it would, there is no reason I can see it does this

**Comment by draconb** [comment]
Turns out CIVL can be neutral to you, but not PEACED, once PEACED, it works fine and lets you hangar.

**Comment by Terif1** [comment]
closing as resolved
