### ISSUE TITLE
MES Issues

### ISSUE THREAD

**Issue by Synirrr** [DraconisCluster/DX-Issues#16]
MES Bugs:
- beaindead spawns
- spawning too often (like every 2-3 minutes)
- exclusion zones not working
- not cleaning up NPCs properly
- Juipiter zones also don’t seem to be setup correctly, stations spawn at the edge of the instance
- TTU is getting cleaned up too fast cause they are too quick to get to their path end

**Comment by Synirrr** [comment]
@ReaperKeeper34

**Comment by ReaperKeeper34** [comment]
Need more info on the Jupiter zones

**Comment by Synirrr** [comment]
Braindead spawns have been fixed. Issue was within MES code itself.

**Comment by draconb** [comment]
Issues should have been resolved with config updates. Options were sometimes resetting back to defaults but now should be good.
