### ISSUE TITLE
Medina -> Sol / Ilus not creating backups on transfer

### ISSUE THREAD

**Issue by draconb** [DraconisCluster/DX-Issues#22]
Transfering in/out of Medina / Ring Space (XM) does not create transfer backups, maybe we could lower medina's auto backup time if its not possible to get transfer backups working?

**Comment by Terif1** [comment]
Nexus controls the on transfer backups manually so can't change that

**Comment by Terif1** [comment]
I'd be down for increasing the frequency of backups a little bit though

**Comment by Synirrr** [comment]
We could add the grid backup function to the gate transfer scripts

**Comment by Terif1** [comment]
oh that's a good point
