### ISSUE TITLE
Assemblers working in PvE Zone (Ganny)

### ISSUE THREAD

**Issue by draconb** [DraconisCluster/DX-Issues#23]
Assemblers are working inside the Gannymade Trade Zone

**Comment by draconb** [comment]
More details in ticket 49444 but gist is you can build/enable assemblers inside the trade zone and they aren't forced off/disabled and you can craft while being immune to npc damage.

**Comment by Terif1** [comment]
We're aware and working on a fix, se technical issues are not helping

**Comment by draconb** [comment]
Comp costs nerfed a while ago so not really relevant anymore with econ changes
