### ISSUE TITLE
Multiple Instances Restarted at 2 AM PST

### ISSUE THREAD

**Issue by subbob** [DraconisCluster/DX-Issues#25]
**TL;DR**
Player reports via ticket that multiple servers observed to shutdown 

**Summary**

Ticket Submission:
> Just a heads up that most if not all the servers went down and came back up automatically at the time Server Backups normally occur (4am EST).
> 
> Might want to double check there isn't a problem with the backup system(s).  That is all

I asked some follow up Qs. Answers:

> There was no notification.  around 4:05 am EST I and a couple others saw their respective servers DC.
> I can only confirm DX1 went down myself FTR.

Comment: Not sure if this is a one-off thing but figured important enough to capture and report for checking out.

Related Ticket: `/tickets show 49847 `

**Comment by draconb** [comment]
I'm confused here... 2 am PST or 4 am EST? PST and EST have a 3 hr gap. 1 am / 4am EST is the normal backup time.

Looks like 1am PST?

**Comment by Synirrr** [comment]
Seems like a one off issue that has not reoccurred.
