### ISSUE TITLE
MES spawns

### ISSUE THREAD

**Issue by BigFloppyJim** [DraconisCluster/DX-Issues#27]
** tl; dr **NPC spawns in dx1 and dx5
--type of issue (bug, fr, etc), short what and why--

** Full info **NPCs are spawning in high speed zones.
--long what and why--

**Screenshots**
--If applicable, add screenshots to help explain your problem.--

**Comment by subbob** [comment]
[MES Issues Spot Reports](<https://discord.com/channels/516135382191177728/1208641921774522398>) thread in ticket-discussions

**Comment by sgtdrew720** [comment]
this should be fixed
