### ISSUE TITLE
Block limits

### ISSUE THREAD

**Issue by BigFloppyJim** [DraconisCluster/DX-Issues#28]
** tl; dr ** players aren't limited to 10 assemblers
--type of issue (bug, fr, etc), short what and why--

** Full info **players can build 11/10 assemblers before the limiter kicks in.
--long what and why--

**Screenshots**
--If applicable, add screenshots to help explain your problem.--

**Comment by Synirrr** [comment]
Assemblers that go over the limit will be forced off. Block limiter is a 3rd party plugin and we therefore have no control over how it operates. PRs into the code base may never be accepted so as of right now not much we can do.
