### ISSUE TITLE
Xela Ticket Transcript Incomplete

### ISSUE THREAD

**Issue by subbob** [DraconisCluster/DX-Issues#29]
**Ticket Transcript Does not Capture All Posts**
I asked a player a series of Qs and for him to reply to each one individually. It recorded his answers but not my Qs.

**Screenshots**
![Screenshot](https://github.com/DraconisCluster/DX-Issues/assets/5113030/4980f0d2-880f-41e4-863f-01085db9f716)
![Transcript](https://github.com/DraconisCluster/DX-Issues/assets/5113030/81ca2020-d3be-42c0-bc2f-49254aa475b8)

**Remarks**
It's probably always done this. I only happened to notice this time as I looked at both my screenshot and the transcript within a short amount of time.

**Comment by Synirrr** [comment]
This is not a DX issue. Please let Alex or Azazel know
