### ISSUE TITLE
MES Braindead

### ISSUE THREAD

**Issue by Terif1** [DraconisCluster/DX-Issues#3]
** tl; dr **
MES spawns are DOA and often behave in unintended ways

** Full info **
Vast numbers of reports have come in showing braindead npcs. No apparent issue exists in the mod.

**Screenshots**
N/A

**Comment by ReaperKeeper34** [comment]
Update: 

With the addition of adding the rival AI NPC remote block as an exception to concealment current rework seems to have a positive effect on the amount of DOA NPC reports.

**Comment by Terif1** [comment]
per #11 (for tracking) seeing some npcs spawn in dx1 probably due to having the files on there

**Comment by Synirrr** [comment]
Included in #16 covering multiple MES issues

**Comment by Terif1** [comment]
closing in favor of #16
