### ISSUE TITLE
MES NPCs Spawn Ranges Too Short

### ISSUE THREAD

**Issue by subbob** [DraconisCluster/DX-Issues#30]
**Threat NPCs spawning well inside of 10km**

**Full info**
- Recent tickets and comments in dx-gamechat reported TTU & TIH ships spawning too close to players
- In the case of TTU, it's resulted in them rapidly closing to within 3km CQB PDC range 
- It happened to me just now while using our Inner Miner in C2, I hit WIN+ALT+R to capture the recording (shared below)
- The TTU NPC spawned in around 6km and got **very close** to within 3km before reaching CPA and opening again

**Reference**
[Player's  Bug Report Thread](https://cdn.discordapp.com/attachments/1209498033192964168/1209498466116706304/TTU_Close_Spawn.mp4?ex=65e72439&is=65d4af39&hm=7ad53af47e271db1623244b61e57a6b53e40484206e25c58a77fc54b389d3983&)

**Video**
[Miner's Dashcam Video](https://cdn.discordapp.com/attachments/1209498033192964168/1209498466116706304/TTU_Close_Spawn.mp4)

**Comment by subbob** [comment]
![Happened Again](https://github.com/DraconisCluster/DX-Issues/assets/5113030/2a37ee75-1709-4618-9787-0621415d95b3)

Another one did the same, spawned closed and CPA was inside 4km while I was writing up this issue report.

**Comment by Synirrr** [comment]
This has been fixed.
