### ISSUE TITLE
DX8 Lidar range limited to 18KM

### ISSUE THREAD

**Issue by williamdemarigny** [DraconisCluster/DX-Issues#32]
Snek discovered that NPC's are not being detected until 18KM using Lidar.

** Full info **
Lidar not working at correct range in DX8

**Screenshots**
(https://discord.com/channels/516135382191177728/1211577171991072779)
Player has provided video of the misconfiguration.

**Comment by BDCarrillo** [comment]
Lidar ammo range is 18km and should be corrected.  Note this was previously masked by an error in determining the maximum AI range.  Ref WC patch note:

Fixed grid AI.MaxTargetingRange (used to gather info on nearby potential targets or obstructions). Throughout WC it was based on the lesser of AI aiming max distance or trajectory of the longest ranged weapon. On grid initialization it was only looking at the trajectory max. This AI.MaxTargetingRange value now updates on weapon removal as well, when it previously did not decrease until a world load event or copy/paste of the grid.

**Comment by Synirrr** [comment]
Lidar Max range has been reconfimed as configured correctly.
![image](https://github.com/DraconisCluster/DX-Issues/assets/82529529/2b142331-27bd-46a4-99d7-3ab6dd3e2363)
![image](https://github.com/DraconisCluster/DX-Issues/assets/82529529/a3fd4c4f-3953-46b9-8039-837497277205)
