### ISSUE TITLE
Components disappeared from inventory

### ISSUE THREAD

**Issue by Dnoxl** [DraconisCluster/DX-Issues#34]
ticket 50225 by ethan.welter

components (144k steelplates, 10k glass) disappeared each upon merging them with another stack of components, occured in DX1

**Comment by Synirrr** [comment]
https://discord.com/channels/516135382191177728/697798386962661457/1214516169029980180

In the future please link the time and instance it occurred so we can check logs.

**Comment by draconb** [comment]
Sounds like a one off bug, haven't heard of other reports. Please re-open if reoccurs
