### ISSUE TITLE
Selling Scan Data at Tycho Removed 7B SC

### ISSUE THREAD

**Issue by subbob** [DraconisCluster/DX-Issues#35]
**Player Sold Scan Data and 7B SC Removed**

** Full info **
Inferno was testing selling Scan Data at Tycho Tech store and that it was properly generating.  He noted his balance prior to starting (21B SC) with a screenshot in the thread.  When he was finished, his balance as 14B SC. I was watching his stream live as he was doing the testing. Neither of us noted when the balance was changed. He only sold 2 scan data (+50M SC) and never bought anything.

- Concern: For players with very high balances (100s of Billions) this could have been happening and was not noticed.
- or it could be a "root cause" for some of the balances out of sync between instances

**Reference**
[Tycho Store Testing](https://discord.com/channels/516135382191177728/1213895266323800094)

**Comment by TEKKONIC** [comment]
![Starting balance](https://github.com/DraconisCluster/DX-Issues/assets/162046898/083a7d04-5d8b-48f4-aea7-63633c713d62)

![Ending balance](https://github.com/DraconisCluster/DX-Issues/assets/162046898/ff313ddf-8df2-4959-8931-068a9f660485)

**Comment by sgtdrew720** [comment]
sounds like instance balance desync, which is a known issue

**Comment by draconb** [comment]
Did you guys do a balance check between instances?

**Comment by TEKKONIC** [comment]
Yes we did dx2 was as shown and the rest were correct

**Comment by Terif1** [comment]
closing as resolved since it was just balance desync, a known issue
