### ISSUE TITLE
Inner PDC ammo vanishing from grid on hanger

### ISSUE THREAD

**Issue by SugerGlider12** [DraconisCluster/DX-Issues#36]
just a claim as i dont have profe

user claims that his pdc ammo vanished while in the hanger over the span of 2 days

**Comment by draconb** [comment]
Likely iim took it or they reloaded. Hangar wouldn't modify it

**Comment by SugerGlider12** [comment]
nether grids have inventory scripts running on them

**Comment by Synirrr** [comment]
This is impossible. Closing as we need proof of the issue occuring.
