### ISSUE TITLE
Grinding RS ToolCore Welder -> Assertion Error

### ISSUE THREAD

**Issue by subbob** [DraconisCluster/DX-Issues#37]
**Assertion Error when Grinding Ramshackle ToolCore Welder**

** Full info **
- Server: Expanse
- Instance: DXIllus
- Upon grinding a RS ToolCore Welder block it generates the pop up error shown in attached image. 
- Repeatable: Yes. I've had it happen twice now. 2 for 2 on this error.
- Both times I chose **Ignore** option and it returned to the game as if it did not happen. The block was gone upon returning to game.
- Update: Returned to game the first time it happened. The 2nd time the client closed out. Probably because it timed out while I left that error box on screen to document the issue.

**Screenshots**
![Assertion Error](https://github.com/DraconisCluster/DX-Issues/assets/5113030/509213cb-d419-4c6f-98bb-139a449f8652)|
![Base Layout](https://github.com/DraconisCluster/DX-Issues/assets/5113030/7c1a7969-7fac-48ae-9905-8f2018daa3bd)
The two RS welders were used to build Advanced Static Drills 2 & 3.

**Comment by Terif1** [comment]
I believe this has been forwarded to the devs by synirr and ash is working on it.

**Comment by draconb** [comment]
TC issues should all be resolved
