### ISSUE TITLE
Weaponcore bug or desync Ticket #50263

### ISSUE THREAD

**Issue by Herzza95** [DraconisCluster/DX-Issues#38]
the expanse, DX2, uss valor/ mellows heavyhauler 8:00-9:00pm. 03-03-24 i think either weaponcore is crapping itself or something weird is going on. was attacked by alf, could not target the attacking ship in any way.. weapons were on and loaded had lidar on ship was using flaks was not allowed to return fire... so went and got my warship same thing i cant target that ship in any way but can target npc's. i can only think of three reasons that would happen one w/c is crapping the bed again. two the ship in question could have left something share to all or three something else funky is going on  pic for reference

**Comment by Terif1** [comment]
this is interesting. was the ship being attacked attackable after a restart or fixship? would guess somewhere the grid's ai is borked, just would need to figure out what causes that for a fix

**Comment by draconb** [comment]
Doesn't seem to be a common issue, please reopen if issue occurs again
