### ISSUE TITLE
Hangar not saving grids

### ISSUE THREAD

**Issue by Dnoxl** [DraconisCluster/DX-Issues#39]
**tl; dr**
Grids disappear on save but dont end up in hangar

**Full info**
Multiple Reports of players saving grids to their Hangar, but their Hangar showing an empty list / the Grid not being there. Issue mainly exists in Kronos as of now.

Reports as of now available in Tickets 50369 and 50370

**Comment by SugerGlider12** [comment]
I was able to unhanger a ship from FH in 3 tho the list did NOT UPDATE ON !fh list a 2nd time
and if i try to run the command to remove the grid again it gives the no data error
![Screenshot 2024-03-09 060747](https://github.com/DraconisCluster/DX-Issues/assets/155582472/e8e84919-d739-4059-b370-c9aaeba58faa)

**Comment by SugerGlider12** [comment]
ok more data
if i save the grid in question back to FH it goes back to the slot it camefrom and the list Doesnt update on removel

**Comment by SugerGlider12** [comment]
!h is working correctly in x3 
!h list shows what i expect
!h load removes the correct grid
!h list shows grid removed
!h save saves grid to newest slot
!h list shows correctly

**Comment by SugerGlider12** [comment]
![Screenshot 2024-03-09 063127](https://github.com/DraconisCluster/DX-Issues/assets/155582472/7fca8f58-e9db-45d0-accb-9d5d0462a91c)
ok issue #3 is ring hanger is no space see picture

**Comment by Dnoxl** [comment]
> ![Screenshot 2024-03-09 063127](https://github.com/DraconisCluster/DX-Issues/assets/155582472/7fca8f58-e9db-45d0-accb-9d5d0462a91c)
> ok issue #3 is ring hanger is no space see picture
> 

Was me being stupid

**Comment by Lutavian** [comment]
![image](https://github.com/DraconisCluster/DX-Issues/assets/29991179/a2e87603-b0ea-4b3f-ac4e-096b403dea01)
There was also this neat report, says that these appeared without him doing anything to the hangar itself (like loading or saving)

**Comment by Terif1** [comment]
are we still seeing any issues with this? from what I understand this should all be fixed

**Comment by Dnoxl** [comment]
only the aftermath of duped grids, and the removal of the duped entries causing the original to be deleted

**Comment by draconb** [comment]
Hanger issues resolved a while ago
