### ISSUE TITLE
Kronos grid duplication

### ISSUE THREAD

**Issue by Dnoxl** [DraconisCluster/DX-Issues#40]
SUS Burstar has received two duplicates with no server crash, they seem to have been different versions of the same grid with atleast one of them being confirmed to be older by the player, the grids have been removed however the origin of the issue is completely unknown

https://discord.com/channels/516135382191177728/1215970997337854032
![image](https://github.com/DraconisCluster/DX-Issues/assets/102689511/f32c1608-5363-4855-95d6-fbb762b8e5e7)

**Comment by Terif1** [comment]
Have we seen any other cases of this? If not then I say we write it off as a freak accident

**Comment by Lutavian** [comment]
I have not but I will mess around the gates later today before we close it out

**Comment by Dnoxl** [comment]
A possible theory is that it was still there from the old kronos, unsure how well supported that is. Also there was another incident with raz19's grid duplicating at the kronos gate, might be that kronos crashed and rolled back before he transitioned out tho

**Comment by draconb** [comment]
This doesn't appear to be a persistent problem
