### ISSUE TITLE
Halley Medium Mining Vehicle BP flaw - RCS placement leading to damage

### ISSUE THREAD

**Issue by nrbrt10** [DraconisCluster/DX-Issues#46]
** tl; dr **
The drive section on the Halley has RCS placed closer than 2 blocks apart leading to self damage.

** Full info **
see tl; dr. Feel free to close if this doesn't qualify as an issue.

**Screenshots**
![image](https://github.com/DraconisCluster/DX-Issues/assets/17500248/df7d7482-5f8f-4d7b-a7ba-03ce27583023)

**Comment by draconb** [comment]
@TAGur1t hey just wanted to let you know this was here, also let me know if you have any issues with updating it or git questions :)

**Comment by draconb** [comment]
Updated a while ago
