### ISSUE TITLE
TTU spawning with no power

### ISSUE THREAD

**Issue by FoxyWoxy7035** [DraconisCluster/DX-Issues#49]
Player reports TTU are spawning with no power, that's all I have.

Ticket reference #51479

**Comment by FoxyWoxy7035** [comment]
Player reports the spawns are working for them again.

**Comment by Synirrr** [comment]
Please close

**Comment by FoxyWoxy7035** [comment]
Sorry for delay, I don't github regularly. I have seen occasional mention of TTU with no power in chat lately from other players, it seems to be a intermittent issue. At least one other mod has noticed this trend as well. I don't know if any action is necessary, just reporting it.
