### ISSUE TITLE
Nation Radar Hits Showing Up Out of Area

### ISSUE THREAD

**Issue by subbob** [DraconisCluster/DX-Issues#5]
** tl; dr **
Issue title is TLDR

** Full info **
A few days ago Radar Hits started showing up again when out of area. They did this when Nations first launched. Then the problem was fixed. Now they are (sometimes) showing up again.

**Screenshots**
[OPA Radar hit while in DX5, 5675km away](https://cdn.discordapp.com/attachments/1021881558879191111/1192840525255032912/image.png?ex=65aa8a4f&is=6598154f&hm=82354650024588127c30c871a2449800e8f8972056eae02b4acf2186332550d7&)

**Comment by Terif1** [comment]
interesting

can you please send a screenshot of the description of the gps you get for the radar hit next time you see this?

I encode the server id into the gps, then parse to get the server id to know if you're same instance or not, want to see if this is still working

**Comment by Terif1** [comment]
if it is, you should see "&8" at the end of the description if it's working right, "&6" would mean it could show up in dx5

**Comment by Terif1** [comment]
or well the encoding/radar hit generation is working fine, the parsing/filter isn't

**Comment by draconb** [comment]
While it can be annoying, its honestly good that they do show up, otherwise no one would ever defend the home nation / know when its being attacked unless there is a huge incentive to stay in the zone itself, which right now means forgoing mining/hunting which is 90% of the game time.

So while I'm hunting at Saturn I see a ping about something in Earth I can choose to go check it out or not, otherwise I'd never know.

That said, I would like to see the radar ping itself be tweaked so unpowered, unmanned grids don't show up, right now some busted grid will send out many pings and be spammy for hours.

**Comment by subbob** [comment]
Per our DM, none of the new Radar Hits have any Description information
![image](https://github.com/DraconisCluster/DX-Issues/assets/5113030/119e4f65-c4bb-47fc-a16d-e39217bd4461)

**Comment by Terif1** [comment]
gonna add this as a todo feature, the way I'm doing obviously needs work

**Comment by Synirrr** [comment]
Has this had any work done on it?

**Comment by Terif1** [comment]
haven't messed with this

**Comment by Terif1** [comment]
it keeps flipping back and forth too whether it works. Very annoying

**Comment by draconb** [comment]
They don't show up if you aren't in nation space **in sol**. If you are in Kronos / Medina / etc they might still show up

**Comment by Terif1** [comment]
https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeWZtdDNtdHp4ZnJ0MmVna21reXZsYjVvb29ueW9sMTg4cjlwMTd4ZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o6MbbwX2g2GA4MUus/giphy.gif

**Comment by Terif1** [comment]
I don't understand anything at this point

**Comment by draconb** [comment]
@Synirrr this was tracking it... originally it was a bug that they were showing up in other zones so *something* changed, but the change broke all cross instance notifications

**Comment by draconb** [comment]
This seems to be some kind of issue when building project on Visual Studio (breaks) while same code works when built from Rider?

VS was release mode vs debug mode in Rider... hard to test w/o breaking prod

**Comment by draconb** [comment]
@Synirrr @Terif1 any ideas?

**Comment by Terif1** [comment]
oh, vs building against release not debug might do it

sure theres other subtle differences as well but that would be my first thing is to look at debug versus release and see whats different

**Comment by Terif1** [comment]
probably something to do with how its managing the dependencies if I were to guess

**Comment by draconb** [comment]
I tried looking at the decompiled code from each and didn't notice much (optimizations here or there), maybe it was another included file or just missed something

**Comment by Terif1** [comment]
I mean somehow for cross instance to be failing, it must be that the way it hooks into nexus is wonky with the vs build

**Comment by Terif1** [comment]
maybe vs is messing with the package/method names somewhere?

**Comment by Terif1** [comment]
looking at it, crunch used the let nexus patch in version of the nexus api as opposed to dependency on it, so best guess is something in the NexusStuff.NexusAPI is being built wrong and failing to register
