### ISSUE TITLE
Bounty NPC's Spawning on top of players

### ISSUE THREAD

**Issue by FoxyWoxy7035** [DraconisCluster/DX-Issues#50]
** tl; dr **
Bounties spawn on top of people

** Full info **
Sources: Ticket #51677, Mavlite

Right now I have at least two reports of the bounty encounter spawning very close to a player and opening fire. In both of these cases the players were in non-combat ships and had their grids nuked. I understand the intended behavior of bounties is to spawn far away from people to prevent this exact interaction.

**Comment by FoxyWoxy7035** [comment]
Additional report in gamechat of a bounty spawning 7km away from someone in dx4

**Comment by draconb** [comment]
Updated 3, 4 and 7 to have boss spawns disabled in MES in game command

/MES.Settings.BossEncounters.EnableSpawns.false

/MES.Debug.ResetZones

**Comment by FoxyWoxy7035** [comment]
Still happening apparently
![image](https://github.com/DraconisCluster/DX-Issues/assets/61330060/d4ba9742-9f8b-4066-bbeb-bd4466891f00)
Ticket#51744
