### ISSUE TITLE
torps exploding on screen 

### ISSUE THREAD

**Issue by SugerGlider12** [DraconisCluster/DX-Issues#9]
https://discord.com/channels/516135382191177728/1195886051001114664

**Comment by Synirrr** [comment]
Have we seen this since this report?

**Comment by SugerGlider12** [comment]
yes i watched moggys grid have torps explode on screen when he was fighing some unn stations around luna ~2-5 days ago
sorry just noticed this

**Comment by Synirrr** [comment]
This seems to have fixed itself
